## Titanic Survival Analysis

#### Library and Dataset Import

In [1]:
import pandas as pd
import numpy as np
titanic = pd.read_csv("titanic.csv")
print("Kütüphaneler ve dataset içe aktarıldı.")

Kütüphaneler ve dataset içe aktarıldı.

#### Exploratory Data Analysis (EDA)

In [2]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
titanic.shape #891 yolcu 12 bilgi

(891, 12)

In [4]:
titanic.info() # demekki yaş,kabin no,bindiği limanda eksik bilgiler var

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
titanic.isnull().sum() #yas:177,kabin no:687,liman bilgisi:2 eksik değer bulunuyor.

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
titanic.nunique() #her sütunda kaç farklı değer olduğunu gösterir.

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [8]:
titanic["Survived"].value_counts()   #hayatta kalan ve kurtulan

Survived
0    549
1    342
Name: count, dtype: int64

In [9]:
titanic["Sex"].value_counts()   #cinsiyet

Sex
male      577
female    314
Name: count, dtype: int64

In [10]:
titanic["Pclass"].value_counts() # sınıfların sayısı

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [11]:
titanic["Age"].value_counts() #yaşlardan kaç tane var.

Age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [12]:
titanic["Embarked"].value_counts() #Hangi limandan bindikleri bilgisi çoğunluk UK ve France dan binmiş

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [13]:
titanic.groupby("Sex")["Survived"].mean() #Kadınlar daha çok kurtulmuş

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [14]:
titanic.groupby("Pclass")["Survived"].mean() #Üst sınıf bilet hayatta kalma şansı daha yüksek

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [15]:
titanic.groupby("Embarked")["Survived"].mean() #C limanında binenler ilginç şekilde hayatta kalma oranı yüksek.Fransadan binenler yani.

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

In [16]:
titanic.tail() # Son 5 satırı gösterir.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [17]:
titanic.groupby("Age")["Survived"].mean()

Age
0.42     1.0
0.67     1.0
0.75     1.0
0.83     1.0
0.92     1.0
        ...
70.00    0.0
70.50    0.0
71.00    0.0
74.00    0.0
80.00    1.0
Name: Survived, Length: 88, dtype: float64

In [18]:
titanic['AgeGroup'] = pd.cut(titanic['Age'], bins=[0, 12, 18, 35, 60, 100],                              ##Bir özelliği gruplara ayırma
                          labels=['Çocuk', 'Genç', 'Genç Yetişkin', 'Yetişkin', 'Yaşlı'])
titanic.groupby('AgeGroup', observed=False)['Survived'].mean()        # Çocukların yaşama oranı yüksek ihtiyarların az.
                                                                    #  genç ve yetişkinlerinde birbirine yakın.

AgeGroup
Çocuk            0.579710
Genç             0.428571
Genç Yetişkin    0.382682
Yetişkin         0.400000
Yaşlı            0.227273
Name: Survived, dtype: float64

In [19]:
titanic.groupby("AgeGroup").size()

C:\Users\enesc\AppData\Local\Temp\ipykernel_14676\2839040172.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby("AgeGroup").size()

AgeGroup
Çocuk             69
Genç              70
Genç Yetişkin    358
Yetişkin         195
Yaşlı             22
dtype: int64

In [21]:
survival= titanic.groupby("Embarked")["Survived"].agg(                   ## agg komutuyla birden fazla özet fonksiyonu çalıştırıyoruz.
    total_count="count",  # Toplam yolcu sayısı
    survived_sum="sum"
)

# Ölenlerin sayısını da ekleyelim
survival["died"] = survival["total_count"] - survival["survived_sum"]

print(survival)

# buda bir yöntem tablo için
pd.crosstab(titanic["Embarked"], [titanic["Survived"],titanic["Sex"]])                   ## buda kısa yöntem çaprazlama

          total_count  survived_sum  died
Embarked
C                 168            93    75
Q                  77            30    47
S                 644           217   427

Survived      0           1
Sex      female male female male
Embarked
C             9   66     64   29
Q             9   38     27    3
S            63  364    140   77